### ISSUE TITLE
Support for Primary Menu with sub-items

### ISSUE THREAD

**Issue by djsiddz2** [denitcoder/wp-theme-zentile#2]
Hi! I have just started using the theme on my [blog](https://thebestcarblogever.com/). While customizing the theme to fit my requirements, I saw that one menu item, which had some sub-items, was not functioning as a dropdown. It was there as a link to the top-level page, and no way to navigate to the sub-pages.

There are a few possible solutions; the ideal one would be that you are able to provide an update with support to display the Primary Menu with sub-items as a dropdown. The other option would be that I change the structure of my blog. Although in the foreseeable future there is a possibility that having support for the menu with sub-items would be a better solution for my blog and for other people using this theme as well.

Please let me know if you will add support for this.

**Comment by denitcoder** [comment]
Hi, I plan to add support for sub-menus this or next week.

**Comment by djsiddz2** [comment]
That's great! Looking forward to it.

Also, the other pages are currently using the same template as posts I noticed. They show the date when the page was created, which is not required. This could also be an enhancement. Should I open a separate issue for this?

**Comment by metlin82** [comment]
отличная идея дизайна, использую ее в данный момент, но единственное очень не хватает возможность оценивать статью и показ просмотров и в конце статьи похожие записи. а так все супер!
