### ISSUE TITLE
icons become very big, when trying out the theme myself

### ISSUE THREAD

**Issue by nici200000** [denitcoder/wp-theme-zentile#20]
Hello developer,
I have got a problem.

I tried to change a little bit in code (locally) but realized it was not very useful so I went back to how the code was at the beginning.
After I installed the theme then, somehow some icons became very big. 
Do not forget, at the end nothing changed, so why these big icons?
So the lens near the searchbar is as big as my screen and down in the bottom the icon near "to the top" (arrow?)  is also the complete size of my Screen.
By the way. I tried installing it afterwards once again as a .zip directly downloaded from Github and it worked and looked normal.
So there has to be a bug somewhere enabling "size changes" of these 2 icons if installed from somewhere else (e.g. locally).
![BigLens](https://user-images.githubusercontent.com/83073771/176651189-0f90e409-d61d-48e3-8703-cbee1ec21859.png)

**Comment by denitcoder** [comment]
@nici200000 Can't reproduce, make sure you run `npm run build` after each file edit or run `npm run watch` before editing. Files in the `assets` directory are not used by the theme directly, instead it uses compiled assets from the `dist` directory (created by the `build` and `watch` commands). Feel free to reopen this issue if the problem persists.
