### ISSUE TITLE
Feature Request : Colorful Categories

### ISSUE THREAD

**Issue by kfazil** [denitcoder/wp-theme-zentile#6]
Hey @denitcoder, I'm continuously watching releases on this theme and I'm also using this theme on my website. I like this theme very much because of the design, less CSS and JS code. I just tried to make the categories coloured with different background colour and text colour. I think you will like this idea of making a category coloured optionally.
![colorfull-category](https://user-images.githubusercontent.com/23123828/99882397-2aa94000-2c46-11eb-8242-c41edcb96282.png)

**Comment by denitcoder** [comment]
Hi @kfazil, thanks for your suggestion, it looks cool, but it will be hard to implement this feature via php. I recommend to use **Customize > Additional CSS** to customize menu/categories, e.g. `.cat-item-8 > a { background: #f00; color: #fff; }`.
