### ISSUE TITLE
Right sidebar в записи

### ISSUE THREAD

**Issue by onadonna** [denitcoder/wp-theme-zentile#8]
Здравствуйте!
Подскажите, пожалуйста, как добавить правый сайдбар на страницу записи?

**Comment by denitcoder** [comment]
Здравствуйте, в последней версии шаблона (1.6) в настройках **WP Admin > Appearance > Customize > Theme Options (Внешний вид > Настроить > Настройки темы)** включите опцию **Always show sidebar / Всегда показывать сайдбар** и добавьте виджеты в правый сайдбар.
